services:
  - rabbitmq

sudo: required

language: java

jdk:
  - oraclejdk8

install: true

before_script:
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
  - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
  - sudo apt-get update
  - sudo apt-get install -y mongodb-org=3.2.10 mongodb-org-server=3.2.10 mongodb-org-shell=3.2.10 mongodb-org-mongos=3.2.10 mongodb-org-tools=3.2.10
  - sleep 15 #mongo may not be ready immediately. See http://docs.travis-ci.com/user/database-setup/#MongoDB
  - mongo --version
  - mongo mydb_test --eval 'db.addUser("travis", "test");'

script: ./gradlew check

after_success:
- ./gradlew cobertura coveralls
- ./gradlew subs-data-model:uploadArchives
- ./gradlew subs-messaging:uploadArchives
- ./gradlew subs-processing-model:uploadArchives

before_install:
- openssl aes-256-cbc -K $encrypted_d65fefe7827f_key -iv $encrypted_d65fefe7827f_iv
  -in gradle_props.tar.enc -out gradle_props.tar -d
- tar xvf gradle_props.tar
