sudo: false

language: java


jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.0-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

before_script:
  - sleep 15

script: ./gradlew check

after_success:
- ./gradlew cobertura coveralls
- ./gradlew subs-data-model:uploadArchives
- ./gradlew subs-messaging:uploadArchives
- ./gradlew subs-processing-model:uploadArchives

before_install:
- openssl aes-256-cbc -K $encrypted_d65fefe7827f_key -iv $encrypted_d65fefe7827f_iv
  -in gradle_props.tar.enc -out gradle_props.tar -d
- tar xvf gradle_props.tar
