sudo: false

language: java


jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - mongodb-upstart
      - sourceline: 'deb [arch=amd64] http://repo.mongodb.org/apt/ubuntu precise/mongodb-org/3.4 multiverse'
        key_url: 'https://www.mongodb.org/static/pgp/server-3.4.asc'
    packages:
      - oracle-java8-installer
      - mongodb-org-server
      - mongodb-org-shell

install: ./gradlew assemble -PaapUsername=$appUsername -PaapPassword=$appPassword

before_script:
  - sleep 15

script: ./gradlew externalCiTest -PaapUsername=$appUsername -PaapPassword=$appPassword

after_success:
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-processing-model:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-api:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-repository:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-progress-monitor:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-dispatcher:uploadArchives


before_install:
- openssl aes-256-cbc -K $encrypted_d65fefe7827f_key -iv $encrypted_d65fefe7827f_iv
  -in gradle_props.tar.enc -out gradle_props.tar -d
- tar xvf gradle_props.tar

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
